name = input("Pls enter your Name: ")
branch = input("Tell me your Branch: ")
gender = input("What is your Gender: ")
collegeName = input("What's your College Name: ")
age = int(input(" Pls enter your Age: "))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",collegeName)
print("Age:",age)

